import enum
from datetime import datetime, timezone
from sqlalchemy import Column, String, Integer, DateTime, ForeignKey, Enum, Text, JSON
from sqlalchemy.orm import relationship

from app.database import Base
from app.utils.common import generate_uuid

sys_now = lambda: datetime.now(timezone.utc)

class SessionType(str, enum.Enum):
    GUIDED_LEARNING = "GUIDED_LEARNING"
    SOCRATIC_QA = "SOCRATIC_QA"

class ChatSession(Base):
    """Contains the history for a particular topic or daily chat, 
    so LangGraph Checkpointer can reload the exact state."""
    __tablename__ = "chat_sessions"
    
    id = Column(String, primary_key=True, default=generate_uuid, index=True)
    student_id = Column(String, ForeignKey("students.id"), nullable=False, index=True)
    node_id = Column(String, ForeignKey("knowledge_nodes.id"), nullable=True, index=True)
    session_type = Column(Enum(SessionType, name="session_type_enum"), default=SessionType.SOCRATIC_QA)
    created_at = Column(DateTime, default=sys_now)
    updated_at = Column(DateTime, default=sys_now, onupdate=sys_now)
    
    messages = relationship("ChatMessage", back_populates="session", cascade="all, delete-orphan")

class SenderRole(str, enum.Enum):
    STUDENT = "STUDENT"
    SYSTEM = "SYSTEM"
    TUTOR_AGENT = "TUTOR_AGENT"

class ChatMessage(Base):
    __tablename__ = "chat_messages"
    
    id = Column(String, primary_key=True, default=generate_uuid, index=True)
    session_id = Column(String, ForeignKey("chat_sessions.id"), nullable=False, index=True)
    sender = Column(Enum(SenderRole, name="sender_role_enum"), nullable=False)
    content_md = Column(Text, nullable=False)
    media_asset_id = Column(String, ForeignKey("media_assets.id"), nullable=True) # if it's an image message
    created_at = Column(DateTime, default=sys_now)
    
    session = relationship("ChatSession", back_populates="messages")
    assessments = relationship("ChatAssessment", back_populates="message")

class AssessmentType(str, enum.Enum):
    IMPLICIT = "IMPLICIT" # Agent evaluated during chat
    EXPLICIT = "EXPLICIT" # Student clicked 'submit answer'

class ChatAssessment(Base):
    """Generated by Assessor Agent based on an answered message"""
    __tablename__ = "chat_assessments"
    
    id = Column(String, primary_key=True, default=generate_uuid, index=True)
    message_id = Column(String, ForeignKey("chat_messages.id"), nullable=True, index=True)
    node_id = Column(String, ForeignKey("knowledge_nodes.id"), nullable=True, index=True)
    assessment_type = Column(Enum(AssessmentType, name="assessment_type_enum"), default=AssessmentType.IMPLICIT)
    is_correct = Column(Integer, default=1) # 1: Yes, 0: No, -1: Partial
    score_delta = Column(Integer, default=0) # e.g. +5 or -10
    diagnosis_json = Column(JSON) # Structured error reasons from Agent
    created_at = Column(DateTime, default=sys_now)
    
    message = relationship("ChatMessage", back_populates="assessments")
