import enum
from datetime import datetime, timezone, date
from sqlalchemy import Column, String, Integer, DateTime, ForeignKey, Enum, Date, Boolean

from app.database import Base
from app.utils.common import generate_uuid

class PlanStatus(str, enum.Enum):
    PENDING = "PENDING"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    MISSED = "MISSED"

class TaskType(str, enum.Enum):
    NEW_KNOWLEDGE = "NEW_KNOWLEDGE"
    REVIEW = "REVIEW"

class PlanItem(Base):
    """Generated by Planner Agent or Schedule Engine"""
    __tablename__ = "plan_items"
    
    id = Column(String, primary_key=True, default=generate_uuid, index=True)
    student_id = Column(String, ForeignKey("students.id"), nullable=False, index=True)
    node_id = Column(String, ForeignKey("knowledge_nodes.id"), nullable=False, index=True)
    scheduled_date = Column(Date, nullable=False, index=True)
    task_type = Column(Enum(TaskType, name="task_type_enum"), default=TaskType.NEW_KNOWLEDGE)
    status = Column(Enum(PlanStatus, name="plan_status_enum"), default=PlanStatus.PENDING)
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))
    completed_at = Column(DateTime, nullable=True)

class LessonStep(str, enum.Enum):
    IMPORT = "IMPORT"
    EXPLAIN = "EXPLAIN"
    EXAMPLE = "EXAMPLE"
    PRACTICE = "PRACTICE"
    SUMMARY = "SUMMARY"
    COMPLETED = "COMPLETED"

class LessonProgress(Base):
    """Tracks the state of a Guided Learning Session"""
    __tablename__ = "lesson_progresses"
    
    id = Column(String, primary_key=True, default=generate_uuid, index=True)
    student_id = Column(String, ForeignKey("students.id"), nullable=False, index=True)
    node_id = Column(String, ForeignKey("knowledge_nodes.id"), nullable=False, index=True)
    current_step = Column(Enum(LessonStep, name="lesson_step_enum"), default=LessonStep.IMPORT)
    is_completed = Column(Boolean, default=False)
    started_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))
    last_interacted_at = Column(DateTime, default=lambda: datetime.now(timezone.utc), onupdate=lambda: datetime.now(timezone.utc))
