"""Init db

Revision ID: 06f8c7e0e6ce
Revises: 
Create Date: 2026-02-25 23:03:46.531085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06f8c7e0e6ce'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('wechat_openid', sa.String(), nullable=True),
    sa.Column('nickname', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parents_id'), 'parents', ['id'], unique=False)
    op.create_index(op.f('ix_parents_phone_number'), 'parents', ['phone_number'], unique=True)
    op.create_index(op.f('ix_parents_wechat_openid'), 'parents', ['wechat_openid'], unique=True)
    op.create_table('students',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('nickname', sa.String(), nullable=False),
    sa.Column('grade', sa.String(), nullable=True),
    sa.Column('learning_style', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_id'), 'students', ['id'], unique=False)
    op.create_index(op.f('ix_students_parent_id'), 'students', ['parent_id'], unique=False)
    op.create_table('media_assets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('access_scope', sa.Enum('PUBLIC', 'PRIVATE', 'TEMPORARY', name='asset_scope_enum'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_assets_id'), 'media_assets', ['id'], unique=False)
    op.create_index(op.f('ix_media_assets_student_id'), 'media_assets', ['student_id'], unique=False)
    op.create_table('test_papers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('snapshot_question_md', sa.Text(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_papers_id'), 'test_papers', ['id'], unique=False)
    op.create_index(op.f('ix_test_papers_student_id'), 'test_papers', ['student_id'], unique=False)
    op.create_table('materials',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('grade', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('publisher', sa.String(), nullable=True),
    sa.Column('material_type', sa.Enum('OFFICIAL', 'EXTERNAL', name='material_type_enum'), nullable=True),
    sa.Column('pdf_asset_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pdf_asset_id'], ['media_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materials_grade'), 'materials', ['grade'], unique=False)
    op.create_index(op.f('ix_materials_id'), 'materials', ['id'], unique=False)
    op.create_index(op.f('ix_materials_subject'), 'materials', ['subject'], unique=False)
    op.create_index(op.f('ix_materials_title'), 'materials', ['title'], unique=False)
    op.create_table('test_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('test_paper_id', sa.String(), nullable=False),
    sa.Column('student_score', sa.Integer(), nullable=True),
    sa.Column('answers_json', sa.Text(), nullable=True),
    sa.Column('grading_json', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['test_paper_id'], ['test_papers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_records_id'), 'test_records', ['id'], unique=False)
    op.create_index(op.f('ix_test_records_test_paper_id'), 'test_records', ['test_paper_id'], unique=False)
    op.create_table('book_activations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('material_id', sa.String(), nullable=False),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('global_progress_pct', sa.Integer(), nullable=True),
    sa.Column('current_health_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_activations_id'), 'book_activations', ['id'], unique=False)
    op.create_index(op.f('ix_book_activations_material_id'), 'book_activations', ['material_id'], unique=False)
    op.create_index(op.f('ix_book_activations_student_id'), 'book_activations', ['student_id'], unique=False)
    op.create_table('knowledge_nodes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('material_id', sa.String(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('seq_num', sa.Integer(), nullable=False),
    sa.Column('pageindex_ref', sa.String(), nullable=True),
    sa.Column('content_md', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['knowledge_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_nodes_id'), 'knowledge_nodes', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_nodes_material_id'), 'knowledge_nodes', ['material_id'], unique=False)
    op.create_index(op.f('ix_knowledge_nodes_parent_id'), 'knowledge_nodes', ['parent_id'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('node_id', sa.String(), nullable=True),
    sa.Column('session_type', sa.Enum('GUIDED_LEARNING', 'SOCRATIC_QA', name='session_type_enum'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['knowledge_nodes.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_id'), 'chat_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_node_id'), 'chat_sessions', ['node_id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_student_id'), 'chat_sessions', ['student_id'], unique=False)
    op.create_table('lesson_progresses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('node_id', sa.String(), nullable=False),
    sa.Column('current_step', sa.Enum('IMPORT', 'EXPLAIN', 'EXAMPLE', 'PRACTICE', 'SUMMARY', 'COMPLETED', name='lesson_step_enum'), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('last_interacted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['knowledge_nodes.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_progresses_id'), 'lesson_progresses', ['id'], unique=False)
    op.create_index(op.f('ix_lesson_progresses_node_id'), 'lesson_progresses', ['node_id'], unique=False)
    op.create_index(op.f('ix_lesson_progresses_student_id'), 'lesson_progresses', ['student_id'], unique=False)
    op.create_table('plan_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('node_id', sa.String(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('task_type', sa.Enum('NEW_KNOWLEDGE', 'REVIEW', name='task_type_enum'), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'MISSED', name='plan_status_enum'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['knowledge_nodes.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_items_id'), 'plan_items', ['id'], unique=False)
    op.create_index(op.f('ix_plan_items_node_id'), 'plan_items', ['node_id'], unique=False)
    op.create_index(op.f('ix_plan_items_scheduled_date'), 'plan_items', ['scheduled_date'], unique=False)
    op.create_index(op.f('ix_plan_items_student_id'), 'plan_items', ['student_id'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('node_id', sa.String(), nullable=True),
    sa.Column('content_md', sa.Text(), nullable=False),
    sa.Column('answer_md', sa.Text(), nullable=True),
    sa.Column('explanation_md', sa.Text(), nullable=True),
    sa.Column('difficulty_level', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.Enum('OFFICIAL', 'VARIANT_GENERATED', 'UPLOADED', name='question_source_type_enum'), nullable=True),
    sa.Column('parent_question_id', sa.String(), nullable=True),
    sa.Column('media_asset_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['media_asset_id'], ['media_assets.id'], ),
    sa.ForeignKeyConstraint(['node_id'], ['knowledge_nodes.id'], ),
    sa.ForeignKeyConstraint(['parent_question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_id'), 'questions', ['id'], unique=False)
    op.create_index(op.f('ix_questions_node_id'), 'questions', ['node_id'], unique=False)
    op.create_table('student_node_states',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('node_id', sa.String(), nullable=False),
    sa.Column('is_unlocked', sa.Boolean(), nullable=True),
    sa.Column('health_score', sa.Integer(), nullable=True),
    sa.Column('last_practiced_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['knowledge_nodes.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_node_states_id'), 'student_node_states', ['id'], unique=False)
    op.create_index(op.f('ix_student_node_states_node_id'), 'student_node_states', ['node_id'], unique=False)
    op.create_index(op.f('ix_student_node_states_student_id'), 'student_node_states', ['student_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('sender', sa.Enum('STUDENT', 'SYSTEM', 'TUTOR_AGENT', name='sender_role_enum'), nullable=False),
    sa.Column('content_md', sa.Text(), nullable=False),
    sa.Column('media_asset_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['media_asset_id'], ['media_assets.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_table('chat_assessments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('assessment_type', sa.Enum('IMPLICIT', 'EXPLICIT', name='assessment_type_enum'), nullable=True),
    sa.Column('is_correct', sa.Integer(), nullable=True),
    sa.Column('score_delta', sa.Integer(), nullable=True),
    sa.Column('diagnosis_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_assessments_id'), 'chat_assessments', ['id'], unique=False)
    op.create_index(op.f('ix_chat_assessments_message_id'), 'chat_assessments', ['message_id'], unique=False)
    op.create_table('student_mistakes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('node_id', sa.String(), nullable=False),
    sa.Column('original_question_id', sa.String(), nullable=True),
    sa.Column('source_message_id', sa.String(), nullable=True),
    sa.Column('error_reason', sa.String(), nullable=True),
    sa.Column('consecutive_correct_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'REVIEWING', 'MASTERED', name='mistake_status_enum'), nullable=True),
    sa.Column('next_review_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['knowledge_nodes.id'], ),
    sa.ForeignKeyConstraint(['original_question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['source_message_id'], ['chat_messages.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_mistakes_id'), 'student_mistakes', ['id'], unique=False)
    op.create_index(op.f('ix_student_mistakes_node_id'), 'student_mistakes', ['node_id'], unique=False)
    op.create_index(op.f('ix_student_mistakes_student_id'), 'student_mistakes', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_mistakes_student_id'), table_name='student_mistakes')
    op.drop_index(op.f('ix_student_mistakes_node_id'), table_name='student_mistakes')
    op.drop_index(op.f('ix_student_mistakes_id'), table_name='student_mistakes')
    op.drop_table('student_mistakes')
    op.drop_index(op.f('ix_chat_assessments_message_id'), table_name='chat_assessments')
    op.drop_index(op.f('ix_chat_assessments_id'), table_name='chat_assessments')
    op.drop_table('chat_assessments')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_student_node_states_student_id'), table_name='student_node_states')
    op.drop_index(op.f('ix_student_node_states_node_id'), table_name='student_node_states')
    op.drop_index(op.f('ix_student_node_states_id'), table_name='student_node_states')
    op.drop_table('student_node_states')
    op.drop_index(op.f('ix_questions_node_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_plan_items_student_id'), table_name='plan_items')
    op.drop_index(op.f('ix_plan_items_scheduled_date'), table_name='plan_items')
    op.drop_index(op.f('ix_plan_items_node_id'), table_name='plan_items')
    op.drop_index(op.f('ix_plan_items_id'), table_name='plan_items')
    op.drop_table('plan_items')
    op.drop_index(op.f('ix_lesson_progresses_student_id'), table_name='lesson_progresses')
    op.drop_index(op.f('ix_lesson_progresses_node_id'), table_name='lesson_progresses')
    op.drop_index(op.f('ix_lesson_progresses_id'), table_name='lesson_progresses')
    op.drop_table('lesson_progresses')
    op.drop_index(op.f('ix_chat_sessions_student_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_node_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_knowledge_nodes_parent_id'), table_name='knowledge_nodes')
    op.drop_index(op.f('ix_knowledge_nodes_material_id'), table_name='knowledge_nodes')
    op.drop_index(op.f('ix_knowledge_nodes_id'), table_name='knowledge_nodes')
    op.drop_table('knowledge_nodes')
    op.drop_index(op.f('ix_book_activations_student_id'), table_name='book_activations')
    op.drop_index(op.f('ix_book_activations_material_id'), table_name='book_activations')
    op.drop_index(op.f('ix_book_activations_id'), table_name='book_activations')
    op.drop_table('book_activations')
    op.drop_index(op.f('ix_test_records_test_paper_id'), table_name='test_records')
    op.drop_index(op.f('ix_test_records_id'), table_name='test_records')
    op.drop_table('test_records')
    op.drop_index(op.f('ix_materials_title'), table_name='materials')
    op.drop_index(op.f('ix_materials_subject'), table_name='materials')
    op.drop_index(op.f('ix_materials_id'), table_name='materials')
    op.drop_index(op.f('ix_materials_grade'), table_name='materials')
    op.drop_table('materials')
    op.drop_index(op.f('ix_test_papers_student_id'), table_name='test_papers')
    op.drop_index(op.f('ix_test_papers_id'), table_name='test_papers')
    op.drop_table('test_papers')
    op.drop_index(op.f('ix_media_assets_student_id'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_id'), table_name='media_assets')
    op.drop_table('media_assets')
    op.drop_index(op.f('ix_students_parent_id'), table_name='students')
    op.drop_index(op.f('ix_students_id'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_parents_wechat_openid'), table_name='parents')
    op.drop_index(op.f('ix_parents_phone_number'), table_name='parents')
    op.drop_index(op.f('ix_parents_id'), table_name='parents')
    op.drop_table('parents')
    # ### end Alembic commands ###
