"""split knowledge node and content

Revision ID: 3defe00fe431
Revises: fc1b4f923b9c
Create Date: 2026-03-05 21:43:46.752338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3defe00fe431'
down_revision: Union[str, Sequence[str], None] = 'fc1b4f923b9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_contents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('knowledge_node_id', sa.String(), nullable=False),
    sa.Column('pi_node_id', sa.String(), nullable=True),
    sa.Column('content_md', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['knowledge_node_id'], ['knowledge_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_contents_id'), 'knowledge_contents', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_contents_knowledge_node_id'), 'knowledge_contents', ['knowledge_node_id'], unique=False)
    op.create_index(op.f('ix_knowledge_contents_pi_node_id'), 'knowledge_contents', ['pi_node_id'], unique=False)
    op.add_column('knowledge_nodes', sa.Column('pi_nodes_json', sa.JSON(), nullable=True))
    op.drop_column('knowledge_nodes', 'content_md')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_nodes', sa.Column('content_md', sa.TEXT(), nullable=True))
    op.drop_column('knowledge_nodes', 'pi_nodes_json')
    op.drop_index(op.f('ix_knowledge_contents_pi_node_id'), table_name='knowledge_contents')
    op.drop_index(op.f('ix_knowledge_contents_knowledge_node_id'), table_name='knowledge_contents')
    op.drop_index(op.f('ix_knowledge_contents_id'), table_name='knowledge_contents')
    op.drop_table('knowledge_contents')
    # ### end Alembic commands ###
