"""Add mapped_pi_nodes to KnowledgeNode

Revision ID: fc1b4f923b9c
Revises: 3892404b1108
Create Date: 2026-03-01 22:29:27.135834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc1b4f923b9c'
down_revision: Union[str, Sequence[str], None] = '3892404b1108'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_nodes', sa.Column('mapped_pi_nodes', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_nodes', 'mapped_pi_nodes')
    # ### end Alembic commands ###
